Portfolio: Add new sections and more responsiveness
romans-adi/portfolio-00 pull request #2
Opened 2023-03-23 21:06 UTC by romans-adi

For this pull request:

- I have added sections Works and About and styles to both sections according to the template design.
- Header elements were changed due to new elements have been added.
- I used grids and flexbox for most of the elements in new sections.
- Project is linted with WebHint, Lighthouse, and StyleLint.

2023-03-23 21:26 UTC, levy002 requested changes
## Hello @romans-adi   , :wave:
### I'm Levy, your PR reviewer

Good job so far :+1: 
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif)

## Status: REQUIRED CHANGES ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @levy002 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-23 21:26 UTC, levy002 commented on index.html
> +          </div>
- [ ] Kindly make sure to insert this background image on the page using CSS background properties in order to follow HTML & CSS best practices and meet the project requirements. Kindly read [this lesson](https://developer.mozilla.org/en-US/docs/Web/CSS/background-image) on how to insert background-image using CSS.

2023-03-23 21:26 UTC, levy002 commented on index.html
> +          </div>
- [ ] Kindly make sure to insert this background image on the page using CSS background properties in order to follow HTML & CSS best practices and meet the project requirements. Kindly read [this lesson](https://developer.mozilla.org/en-US/docs/Web/CSS/background-image) on how to insert background-image using CSS.

2023-03-23 21:26 UTC, levy002 commented on assets/css/styles.css
> +}
- [ ]  KIndly make sure to align the projects by using CSS Grid Layout in order to meet the project requirements. Please read these lessons ([lesson-1](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout) and [lesson-2](https://css-tricks.com/snippets/css/complete-guide-grid/)) to understand how to align content using CSS GRID LAYOUT.

2023-03-24 16:20 UTC, OyePriscilla approved these changes
Hi @romans-adi  👍 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![200](https://user-images.githubusercontent.com/103386183/196424328-985f6e98-f7c6-4cf9-bafe-158436f70560.gif)

## Highlights
Displayed the project section with CSS grid property ✔️
Made all required change ✔️
Used images and background-image to enhance the look of the website ✔️

## Optional suggestions

- [ ] Kindly fill in the `Show your support` section of the Readme file and also remove the template text from the `License` section. 👍 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-24 16:50 UTC, merged