Add contact form
romans-adi/portfolio-00 pull request #3
Opened 2023-03-29 23:48 UTC by romans-adi

- In this project, I added the Contacts section with a heading/message and form to submit.

- Below this form, I placed a footer with social media icons and the image between two sections.

- Styles were applied to the new section and footer.

- The button in the form has a "submit" type and is connected to the absolute URL, which processes an action for collecting data.

2023-03-29 23:55 UTC, mahbubul14 reviewed
# Invalid Code Review Request

**Hi @romans-adi** 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

You have submitted a project, that has linter errors. Kindly fix the issue.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **Does not count** into the code reviews limit._
```

2023-03-30 00:26 UTC, Strangeal requested changes
Hi @romans-adi, @BenMKT and @diarisdiakite, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![Alt Text](https://media.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif)
## Highlights
Used GitHub flow ✅
Descriptive PR summary ✅
Used linters ✅


## Required Changes ♻️
- [ ] Kindly change your icons to match that of the Figma template.
Figma:
<img width="542" alt="Screenshot 2023-03-29 at 17 12 10" src="https://user-images.githubusercontent.com/107192076/228697096-6561dfd5-8260-409b-bb2f-951e03f52c84.png">

Your design:
<img width="327" alt="Screenshot 2023-03-29 at 17 12 35" src="https://user-images.githubusercontent.com/107192076/228697108-b6ff0495-2f36-462b-ac1a-e457dd3c0f4f.png">

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-30 00:26 UTC, Strangeal commented on index.html
> +                <label for="message"><textarea id="message" maxlength="500" placeholder="Hey I’d like to connect to..." required></textarea></label>
[OPTIONAL]
 Please remove the `label` tags from the form. Instead, you can use `aria-label` for the sake of accessibility. If there is no visible name for an `input` element you should use `aria-label` instead of having an empty `label` tags

2023-03-30 01:45 UTC, abdulhamiid requested changes
# Status: Required Changes :recycle:
Hi @romans-adi 👋, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, I really appreciate the effort you put in! but there are still some which haven't been addressed yet.

![](https://media.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif)

## Highlights 🌟

- ✔️ Descriptions are very descriptive
- ✔️ Linters checks are passing
- ✔️ Use GitHub Flow
- ✔️ Meaningful commit messages.

## Required Changes ♻️
_Please kindly check the comments under the review._

## Optional suggestions 🤷‍♂️
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-30 01:45 UTC, abdulhamiid commented on index.html
> +            </ul>
Figma
![image](https://user-images.githubusercontent.com/78251927/228705694-b415d834-9c47-4997-99df-794fb26c08a5.png)

Your design
![image](https://user-images.githubusercontent.com/78251927/228705556-b0cfeac5-9865-4b76-b330-166f4e5c1a81.png)

All the icons in your design are not displaying. Please, let's fix the issues in the design so that it matches [the templates in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1). 💪

2023-03-30 02:38 UTC, merged